// svelte-local-dev/src/components/About.svelte
<div>
  <h1 class="text-xl font-bold">About this app</h1>
  <p class="mt-4">
    This is an SPA made with
    <a href="https://miragejs.com">Mirage</a>
    and
    <a href="https://svelte.dev/">Svelte.</a>
    It has two routes to help demonstrate how Mirage's in-memory database
    enables realistic data fetching and persisting during a single application
    session.
  </p>
  <p class="mt-4">
    Mirage's state is reset whenever the application is reloaded.
  </p>
</div>

// vue-cli-local-dev-and-cypress/src/components/About.vue
<template lang="html">
  <div>
    <h1 class="text-xl font-bold">About this app</h1>
    <p class="mt-4">
      This is an SPA made with <a href="https://miragejs.com">Mirage</a> and
      <a href="https://vuejs.org">Vue</a>. It has two routes to help demonstrate
      how Mirage's in-memory database enables realistic data fetching and
      persisting during a single application session.
    </p>
    <p class="mt-4">
      Mirage's state is reset whenever the application is reloaded.
    </p>
  </div>
</template>
