// react-local-dev-and-cypress/src/App.js
import React from "react";
import "./App.css";
import {
  BrowserRouter as Router,
  Switch,
  Route,
  NavLink
} from "react-router-dom";
import Home from "./components/Todos";
import About from "./components/About";

export default function App() {
  return (
    <div id="app" className="bg-gray-300 h-screen pt-8">
      <Router>
        <div className="max-w-sm mx-auto">
          <header className="pb-8">
            <NavLink
              exact
              to="/"
              className="pb-1 mr-4"
              activeClassName="border-b-2 border-gray-700"
            >
              Home
            </NavLink>
            <NavLink
              to="/about"
              className="pb-1"
              activeClassName="border-b-2 border-gray-700"
            >
              About
            </NavLink>
          </header>

          <Switch>
            <Route exact path="/">
              <Home />
            </Route>
            <Route path="/about">
              <About />
            </Route>
          </Switch>
        </div>
      </Router>
    </div>
  );
}

// svelte-local-dev/src/App.svelte
<script>
  import { Router, Link, Route } from "svelte-routing";
  import About from "./components/About.svelte";
  import Todos from "./components/Todos.svelte";

  export let url = "";

  const propagateClass = ({ baseClass, activeClass }) => ({ isCurrent }) => {
    return { class: `${baseClass}${isCurrent ? " " + activeClass : ""}` };
  };
</script>

<Router {url}>
  <div class="text-gray-900 bg-gray-300 h-screen pt-8">
    <div class="max-w-sm mx-auto">
      <header class="pb-8">
        <Link
          to="/"
          getProps={propagateClass({
            baseClass: 'pb-1 mr-4',
            activeClass: 'border-b-2 border-gray-700'
          })}>
          Home
        </Link>
        <Link
          to="/about"
          getProps={propagateClass({
            baseClass: 'pb-1',
            activeClass: 'border-b-2 border-gray-700'
          })}>
          About
        </Link>
      </header>

      <Route path="about" component={About} />
      <Route path="/">
        <Todos />
      </Route>
    </div>
  </div>
</Router>
